apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  # Here is where we specify the exact configuration of a pod that we want this deployment to create
  template:
    metadata:
      labels:
        app: query
    # pod spec or a pod config file, similar when we create a single pod via yaml
    spec:
      containers:
        - name: query
          image: andres1997/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
